AWSTemplateFormatVersion: '2022-03-30'

Parameters:
  KeyName: kessekey
  VpcId: vpc-0ce8e68805f271af4
Resources:
  SimpleInstance 1 :
    Condition: Launch1
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0c02fb55956c7d316
      NetworkInterfaces:
        AssociatePublicIpAddress: 'true'
        DeleteOnTermination: 'true'
  Instance2:
    Condition: Launch2
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0f9a92942448ac56f
      InstanceType: t2.micro
      NetworkInterfaces:
        AssociatePublicIpAddress: 'true'
        DeleteOnTermination: 'true'
  SimpleInstanceSg:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: vpc-0ce8e68805f271af4
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        FromPort: '443'
        ToPort: '443'
        CidrIp: 10.0.0.0/28
        SecurityGroupEgress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 10.0.0.0/28
  
  Outputs:
  InstanceId: !Ref'EC2Instance'
    
  AZ:
    Value: !GetAtt [EC2Instance, PublicDnsName]
  PublicIP:
    Value: !GetAtt [EC2Instance, PublicIp]
